[workspace]
members = [
    # binary
    "loader",
    "kernel",
    # library
    "bootinfo",
    "io", 
    "print",
    "ports",
    "interrupts",
    "paging",
    "dma",
    "atapi",
    "heap", 
    "TSC",
    "result",
]

resolver = "3"

[profile.release]
lto = true
opt-level = "z" 
codegen-units = 1
strip = "symbols"
panic = "abort"
