[workspace]
members = [
    "loader",
    "io",
    "ports",
    "interrupts",
    "paging",
    "dma",
    "atapi"
]

resolver = "3"

[profile.release]
lto = true
opt-level = "z" 
codegen-units = 1
strip = "symbols"
panic = "abort"