[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
io ={ path = "../io" }
interrupts ={ path = "../interrupts" }
ports ={ path = "../ports" }
paging ={ path = "../paging" }
dma ={ path = "../dma" }
atapi ={ path = "../atapi" }
result = { path = "../result" }